export const BIBLE_BOOKS = [
  "Genesis",
  "Exodo",
  "Levitico",
  "Numeros",
  "Deuteronomio",
  "Josue",
  "Juizes",
  "Rute",
  "1 Samuel",
  "2 Samuel",
  "1 Reis",
  "2 Reis",
  "1 Cronicas",
  "2 Cronicas",
  "Esdras",
  "Neemias",
  "Ester",
  "Jo",
  "Salmos",
  "Proverbios",
  "Eclesiastes",
  "Cantares",
  "Isaias",
  "Jeremias",
  "Lamentacoes",
  "Ezequiel",
  "Daniel",
  "Oseias",
  "Joel",
  "Amos",
  "Obadias",
  "Jonas",
  "Miqueias",
  "Naum",
  "Habacuque",
  "Sofonias",
  "Ageu",
  "Zacarias",
  "Malaquias",
  "Mateus",
  "Marcos",
  "Lucas",
  "Joao",
  "Atos",
  "Romanos",
  "1 Corintios",
  "2 Corintios",
  "Galatas",
  "Efesios",
  "Filipenses",
  "Colossenses",
  "1 Tessalonicenses",
  "2 Tessalonicenses",
  "1 Timoteo",
  "2 Timoteo",
  "Tito",
  "Filemom",
  "Hebreus",
  "Tiago",
  "1 Pedro",
  "2 Pedro",
  "1 Joao",
  "2 Joao",
  "3 Joao",
  "Judas",
  "Apocalipse"
] as const;

export function bookOrder(book: string) {
  const index = BIBLE_BOOKS.indexOf(book as (typeof BIBLE_BOOKS)[number]);
  if (index < 0) {
    throw new Error(`Unknown Bible book: ${book}`);
  }

  return index + 1;
}
